"use client";

import Header from '@/components/Header';
import { FAQs } from '@/components/FAQs';

export default function FaqsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />
      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-8 text-center">
            Frequently Asked Questions
          </h1>
          <FAQs />
        </div>
      </main>
      <footer className="bg-accent h-36 w-full flex items-center justify-center p-4">
        <p className="text-black text-center text-xs sm:text-sm max-w-2xl">
          This health result is generated by an AI-based symptom checker and is NOT a medical diagnosis.
          Information provided is for educational and awareness purposes only.
        </p>
      </footer>
    </div>
  );
}
