import Header from '@/components/Header';
import { HeroSection } from '@/components/HeroSection';
import { SymptomChecker } from '@/components/SymptomChecker';
import { ContactSection } from '@/components/ContactSection';

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />
      <main className="flex-grow">
        <HeroSection>
          <SymptomChecker />
        </HeroSection>
        <ContactSection />
      </main>
      <footer className="bg-accent h-36 w-full flex items-center justify-center p-4">
        <p className="text-black text-center text-xs sm:text-sm max-w-2xl">
          This health result is generated by an AI-based symptom checker and is NOT a medical diagnosis. 
          Information provided is for educational and awareness purposes only.
        </p>
      </footer>
    </div>
  );
}
